# db/seeds_data/cities.rb
CITIES = [
  "Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg",
  "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims", "Le Havre",
  "Cergy-Pontoise", "Saint-Étienne", "Toulon", "Angers", "Grenoble", "Dijon",
  "Nîmes", "Aix-en-Provence", "Saint-Quentin-en-Yvelines", "Brest",
  "Le Mans", "Amiens", "Tours", "Limoges", "Clermont-Ferrand", "La Rochelle",
  "Villeurbanne", "Besançon", "Orléans", "Metz", "Pau", "Rouen", "Mulhouse",
  "Perpignan", "Caen", "Boulogne-Billancourt", "Nancy", "Argenteuil",
  "Saint-Denis", "Roubaix", "Tourcoing", "Montreuil", "Avignon", "Nanterre",
  "Vitry-sur-Seine", "Créteil", "Dunkirk", "Poitiers", "Asnières-sur-Seine",
  "Courbevoie"
]

CITIES_BORDEAUX = [
  "Mérignac",
  "Pessac",
  "Talence",
  "Villenave-d'Ornon",
  "Bègles",
  "Le Bouscat",
  "Gradignan",
  "Cenon",
  "Lormont",
  "Floirac",
  "Saint-Médard-en-Jalles",
  "Eysines",
  "Blanquefort",
  "Bruges",
  "Saint-André-de-Cubzac",
  "Carbon-Blanc",
  "Artigues-près-Bordeaux",
  "Ambarès-et-Lagrave",
  "Cadaujac",
  "La Teste-de-Buch",
  "Le Haillan",
  "Le Taillan-Médoc",
  "Cestas",
  "Saint-Loubès",
  "Le Pian-Médoc",
  "Martignas-sur-Jalle",
  "Parempuyre",
  "Saint-Jean-d'Illac",
  "Léognan",
  "Sainte-Eulalie",
  "Sadirac",
  "Saint-Aubin-de-Médoc",
  "Arsac",
  "Izon",
  "Pompignac",
  "Saint-André-de-Cubzac",
  "Saint-Sulpice-et-Cameyrac",
  "Saint-Louis-de-Montferrand",
  "Beautiran",
  "Sainte-Hélène",
  "Fargues-Saint-Hilaire",
  "Vayres",
  "Saint-Médard-d'Eyrans",
  "Quinsac",
  "Saint-Médard-de-Guizières",
  "La Sauve",
  "Sainte-Foy-la-Grande",
  "Camblanes-et-Meynac",
  "Aubie-et-Espessas",
  "Targon"
]
