# config/meta.yml
title: "Not Solo - Une app pour ne plus être solo"
description: "Ne restez plus solo! Utilisez Not Solo pour trouver des gens qui partagent vos passions et vos centres d'intérêt."
image: "https://res.cloudinary.com/dpwgobuir/image/upload/v1688544134/fsuoh9a4wtqmluhisqrg.jpg"
